import React from 'react';
import { Box, Card, Typography, TextField, FormControlLabel, Checkbox } from '@mui/material';
import { Check, Shield, Zap, GitFork } from 'lucide-react';
import EnvironmentSelection from '../../EnvironmentSelection';
import SearchableSelect from '../../SearchableSelect';

export default function StepOrigin({
  roleType, setRoleType,
  selectedOrgNodeId, setOrgNode, orgNodes,
  selectedParentIds, setSelectedParentIds, allRoles,
  roleName, setRoleName, handleRoleNameBlur,
  description, setDescription,
  environmentId, setEnvironmentId, filteredEnvironments,
  accessDomainId, setAccessDomainId, accessDomains,
  critical, setCritical, setIsCriticalManuallySet,
  isEditMode, permissions, context = {} as any, isReadOnly,
  allAccessDomains
}) {

  return (
    <Card sx={{ p: 3 }}>
      <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 2 }}>Role Origin</Typography>
      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(3, 1fr)' }, gap: 2, mb: 3 }}>
        {[
          { type: 'ORG_BASED', icon: Zap, label: 'Org-Based Role', desc: 'Auto-generated from an Org Structure node', color: 'primary.main', disabled: permissions?.isSuperAdmin ? false : (permissions && !permissions.canManageOrgRoles) },
          { type: 'SINGLE', icon: Shield, label: 'Single Role', desc: 'A custom role containing specific restrictions', color: 'info.main', disabled: permissions?.isSuperAdmin ? false : (permissions && !permissions.canManageSingleRoles) },
          { type: 'DRAGE', icon: GitFork, label: 'DRAGE Role', desc: 'Automated dynamic role generated by the DRAGE engine', color: 'secondary.main', disabled: true },
        ].map(opt => {
          const isSelected = roleType === opt.type;
          const isDisabled = opt.disabled || isEditMode || isReadOnly;
          return (
            <Box
              key={opt.type}
              onClick={() => !isDisabled && setRoleType(opt.type)}
              sx={{
                p: 2,
                borderRadius: 1.5,
                border: '1px solid',
                borderColor: isSelected ? opt.color : 'divider',
                bgcolor: isSelected ? 'action.hover' : 'transparent',
                cursor: isDisabled ? 'not-allowed' : 'pointer',
                opacity: isDisabled && !isSelected ? 0.5 : 1,
                transition: 'all 0.2s',
                display: 'flex',
                flexDirection: 'column',
                gap: 0.5,
                '&:hover': {
                  borderColor: isDisabled ? 'none' : isSelected ? opt.color : 'action.active',
                }
              }}
            >
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <opt.icon size={18} color={opt.color} />
                <Typography variant="body1" sx={{ fontWeight: 700 }}>{opt.label}</Typography>
                {isSelected && <Check size={14} color="#10b981" style={{ marginLeft: 'auto' }} />}
              </Box>
              <Typography variant="body2" color="text.secondary">{opt.desc}</Typography>
            </Box>
          );
        })}
      </Box>

      {roleType === 'ORG_BASED' && (
        <Box sx={{ mb: 3 }}>
          <SearchableSelect
            options={[
              { value: '', label: 'None' },
              ...orgNodes.map(n => ({
                value: n.ID,
                label: `${n.name} (${n.type?.name || ''})`
              }))
            ]}
            value={selectedOrgNodeId}
            onChange={val => setOrgNode(val)}
            label="Select Org Node"
            disabled={isEditMode || isReadOnly}
            sx={{ maxWidth: 400 }}
          />
        </Box>
      )}

      {roleType === 'SINGLE' && (
        <Box sx={{ mb: 3 }}>
          <SearchableSelect
            options={allRoles
              .filter(r => r.ID !== context.roleId)
              .map(r => ({
                value: r.ID,
                label: r.name
              }))}
            value={selectedParentIds}
            onChange={vals => setSelectedParentIds(vals)}
            label="Inherit from Roles (Multiple Select)"
            multiple
            disabled={isReadOnly || (selectedParentIds && selectedParentIds.length > 0)}
          />
        </Box>
      )}

      <Box sx={{ borderTop: '1px solid', borderColor: 'divider', pt: 3, display: 'flex', flexDirection: 'column', gap: 2 }}>
        <TextField
          label="Role Name"
          size="small"
          fullWidth
          placeholder="e.g. ROLE_DE_FINANCE"
          value={roleName}
          onChange={e => setRoleName(e.target.value)}
          onBlur={handleRoleNameBlur}
          disabled={isEditMode || isReadOnly}
        />
        <TextField
          label="Description"
          size="small"
          fullWidth
          placeholder="Optional description"
          value={description}
          onChange={e => setDescription(e.target.value)}
          disabled={isReadOnly}
        />
        <EnvironmentSelection
          value={environmentId}
          onChange={setEnvironmentId}
          disabled={isReadOnly}
          sx={{ mt: 1 }}
        />
        <Box sx={{ mt: 1 }}>
          <SearchableSelect
            options={(() => {
              if (accessDomains.length === 0 || !accessDomains.some(d => d.ID === accessDomainId)) {
                const matchedName = (allAccessDomains || []).find(d => d.ID === accessDomainId)?.name || accessDomainId;
                return [{ value: accessDomainId, label: matchedName }];
              }
              return accessDomains.map(ctx => ({
                value: ctx.ID,
                label: ctx.name
              }));
            })()}
            value={accessDomainId}
            onChange={val => setAccessDomainId(val)}
            label="Access Domain"
            required
            disabled={isReadOnly || (selectedParentIds && selectedParentIds.length > 0)}
          />
        </Box>
        <FormControlLabel
          control={
            <Checkbox
              checked={critical}
              onChange={e => {
                setCritical(e.target.checked);
                setIsCriticalManuallySet(true);
              }}
              color="error"
              disabled={isReadOnly}
            />
          }
          label={
            <Box>
              <Typography variant="body2" sx={{ fontWeight: 600 }}>Critical Status</Typography>
              <Typography variant="caption" color="text.secondary">Flag this role as high-risk/critical authorization</Typography>
            </Box>
          }
        />
      </Box>
    </Card>
  );
}
